services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mongo-network

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo
    networks:
      - mongo-network

# ✅ Make sure the network is defined at the bottom
networks:
  mongo-network:
    driver: bridge
